# Generated by Django 5.2.3 on 2025-07-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='image',
            field=models.ImageField(null=True, upload_to='Other_images/'),
        ),
    ]
