# Generated by Django 5.2.3 on 2025-07-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_other_image_alter_other_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tracking', models.CharField(blank=True, max_length=100, unique=True)),
                ('TypeLivraison', models.CharField(choices=[('0', 'Domicile'), ('1', 'Stopdesk')], max_length=1)),
                ('TypeColis', models.CharField(choices=[('0', 'Normal'), ('1', 'Echange')], max_length=1)),
                ('Confrimee', models.CharField(blank=True, default='', max_length=1)),
                ('Client', models.CharField(max_length=100)),
                ('MobileA', models.CharField(max_length=20)),
                ('MobileB', models.CharField(blank=True, max_length=20)),
                ('Adresse', models.CharField(max_length=255)),
                ('IDWilaya', models.CharField(max_length=2)),
                ('Commune', models.CharField(max_length=100)),
                ('Total', models.CharField(max_length=20)),
                ('Note', models.TextField(blank=True)),
                ('TProduit', models.CharField(max_length=255)),
                ('Source', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
