# Generated by Django 5.2.3 on 2025-07-10 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other',
            name='image',
        ),
    ]
