# Generated by Django 5.2.3 on 2025-07-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_other_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WilayaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDWilaya', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('delivery_home', models.IntegerField(null=True)),
                ('delivery_office', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='Commune',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='TypeColis',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='TypeLivraison',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
