# Generated by Django 5.2.3 on 2025-07-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_wilayainfo_order_quantity_alter_order_commune_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='conferme',
            field=models.BooleanField(default=False),
        ),
    ]
