# Generated by Django 5.2.3 on 2025-07-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_conferme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='conferme',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
