# Generated by Django 5.2.3 on 2025-07-11 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_conferme'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 11, 0, 34, 39, 355254, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
